# Generated by Django 4.0.4 on 2022-05-23 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_avance_cout_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sautage',
            name='foration_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.fourations'),
        ),
    ]
