# Generated by Django 4.0.4 on 2022-05-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_sautage_foration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sautage',
            name='foration_id',
        ),
    ]
