# Generated by Django 4.0.4 on 2022-05-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_fourations_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourations',
            name='machine',
        ),
    ]
