# Generated by Django 3.1.14 on 2022-05-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_fourations_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='aei',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='ligne_tir',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
