# Generated by Django 3.1.14 on 2022-05-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_auto_20220524_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='avance_actuel',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='avance_sautage',
        ),
    ]
