# Generated by Django 3.1.14 on 2022-05-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_pfourations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pfourations',
        ),
    ]
