# Generated by Django 3.1.14 on 2022-05-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_delete_pfourations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pfourations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('RT/SB', 'RT/SB'), ('RT/SA2', 'RT/SA2'), ('INT1/2', 'INT1/2'), ('INT2/4', 'INT2/4'), ('INT3/4', 'INT3/4'), ('INT3/5', 'INT3/5'), ('INT5/6', 'INT5/6'), ('INT4/5', 'INT4/5'), ('INT2/3', 'INT2/3'), ('INTSA2/C0', 'INTSA2/C0'), ('RT/C0', 'RT/C0'), ('RT/C2', 'RT/C2'), ('RT/C3', 'RT/C3'), ('RT/C4', 'RT/C4'), ('RT/C5', 'RT/C5')], max_length=150)),
                ('panneau', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7'), ('P8', 'P8')], max_length=150)),
                ('largeur', models.CharField(max_length=255)),
                ('hauteur', models.CharField(max_length=255)),
                ('tranche', models.CharField(max_length=255)),
                ('diametre', models.CharField(max_length=255)),
                ('longueur', models.CharField(max_length=50)),
                ('de', models.CharField(max_length=255)),
                ('dr', models.CharField(max_length=255)),
                ('espacement', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
