# Generated by Django 3.1.14 on 2022-05-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_pfourations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfourations',
            name='dr',
        ),
    ]
