# Generated by Django 3.1.14 on 2022-05-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_pfourations_densite_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='sautage',
            name='num_com',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.fourations'),
        ),
    ]
