# Generated by Django 3.1.14 on 2022-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_avance_fouration_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='fouration_id',
        ),
        migrations.AddField(
            model_name='avance',
            name='machine',
            field=models.CharField(choices=[('7500/1', '7500/1'), ('7500/2', '7500/2'), ('PH1', 'PH1'), ('PH2', 'PH2'), ('D11', 'D11'), ('E.E', 'E.E')], default=2, max_length=150),
            preserve_default=False,
        ),
    ]
