# Generated by Django 3.1.14 on 2022-06-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_auto_20220531_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cout',
        ),
    ]
