# Generated by Django 3.1.14 on 2022-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0022_delete_cout'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourations',
            name='observation',
            field=models.CharField(choices=[('LABRIKIYINE', 'LABRIKIYINE'), ('LABHIRA', 'LABHIRA')], default=2, max_length=150),
            preserve_default=False,
        ),
    ]
