# Generated by Django 3.1.14 on 2022-06-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0023_fourations_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourations',
            name='machine',
        ),
    ]
