# Generated by Django 3.1.14 on 2022-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0025_fourations_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='sautage',
            name='nammonix',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sautage',
            name='nartifice',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sautage',
            name='ntovex',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
